// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	ModifiedAt time.Time
	UserID     uuid.UUID
	ProductID  uuid.UUID
}
