// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	ModifiedAt  time.Time
	CreatorID   uuid.UUID
	Name        string
	Price       int32
	Description string
}
