name: Run Unit Test

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservices:
          - user_service
          - product_service
          - order_service
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"

      - name: Install Goose
        run: curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh

      - name: Execute Test Cases
        run: |
          cd ./src/${{ matrix.microservices }}
          bash run_unit_test.sh
